name: minimal_mvn
description: A minimal state management solution for Flutter apps using the Model-View-Notifier (MVN) pattern
version: 1.0.2
repository: https://github.com/alesalv/minimal
homepage: https://github.com/alesalv/minimal

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

topics:
  - state-management
  - mvn
  - dependency-injection
  - architecture

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
