name: Deploy Example to Pages

on:
  release:
    types: [published]
  # Keeping manual trigger for testing
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install FVM
        run: |
          dart pub global activate fvm
          fvm install
          fvm flutter --version

      - name: Get dependencies
        run: fvm flutter pub get
        working-directory: example

      - name: Build Web
        run: fvm flutter build web --base-href "/minimal/"
        working-directory: example

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: example/build/web
